Areas/Admin/Controllers/BrandController.cs
using HotelBooking.Models;
using HotelBooking.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HotelBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class BrandController : Controller
    {
        private readonly DataContext _dataContext;

        public BrandController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _dataContext.Brands.OrderByDescending(p => p.Id).ToListAsync());
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrandModel brand)
        {
            if (ModelState.IsValid)
            {
                //thêm dữ liệu
                brand.Slug = brand.Name.Replace(" ", "-");
                var slug = await _dataContext.Brands.FirstOrDefaultAsync(p => p.Slug == brand.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "Thương hiệu đã có trong database");
                    return View(brand);
                }

                //_dataContext.Products.Add(product);
                _dataContext.Add(brand);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Thêm thành công";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Model có một vài thứ đang bị lỗi";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }

                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }
            return View(brand);
        }
        public async Task<IActionResult> Delete(int Id)
        {
            BrandModel brand = await _dataContext.Brands.FindAsync(Id);
            _dataContext.Brands.Remove(brand);
            await _dataContext.SaveChangesAsync();
            TempData["error"] = "thương hiệu đã xóa";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int Id)
        {
            BrandModel brand = await _dataContext.Brands.FindAsync(Id);
            return View(brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BrandModel brand)
        {
            if (ModelState.IsValid)
            {
                //thêm dữ liệu
                brand.Slug = brand.Name.Replace(" ", "-");
                var slug = await _dataContext.Brands.FirstOrDefaultAsync(p => p.Slug == brand.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "Danh mục đã có trong database");
                    return View(brand);
                }

                //_dataContext.Products.Add(product);
                _dataContext.Update(brand);
                await _dataContext.SaveChangesAsync();
                TempData["success"] = "Cập nhật thành công";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Model có một vài thứ đang bị lỗi";
                List<string> errors = new List<string>();
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }

                string errorMessage = string.Join("\n", errors);
                return BadRequest(errorMessage);
            }
            return View(brand);
        }
    }
}

Controllers/BrandController.cs
using HotelBooking.Models;
using HotelBooking.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HotelBooking.Controllers
{
	public class BrandController : Controller
	{
		private readonly DataContext _dataContext;
		public BrandController(DataContext context)
		{
			_dataContext = context;
		}
		
		public async Task<IActionResult> Index(string Slug = "")
		{
			// Tìm kiếm Category dựa trên Slug
			BrandModel brand = _dataContext.Brands
				.Where(c => c.Slug == Slug)
				.FirstOrDefault();

			// Nếu không tìm thấy Category, chuyển hướng về trang Index
			if (brand == null) return RedirectToAction("Index");

			// Lấy danh sách sản phẩm theo CategoryId và sắp xếp giảm dần theo Id
			var productsByBrand = _dataContext.Products
				.Where(p => p.BrandId == brand.Id)  // Lấy danh sách sản phẩm
				.OrderByDescending(p => p.Id);             // Sắp xếp theo Id giảm dần

			// Trả về view với danh sách sản phẩm
			return View(await productsByBrand.ToListAsync());
		}
	}
}

Areas/Admin/Views/Brand/Create.cshtml
@model BrandModel
@{
    ViewData["title"] = "Create Brand";
}
<h4>Create brand</h4>
<div class="col-md-9">
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger">
            <div class="form-group">
                <label>
                    Name
                </label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>

            <div class="form-group">
                <label>
                    Description
                </label>
                <textarea asp-for="Description" class="form-control"></textarea> <!-- Sửa lại thẻ textarea -->
                <span asp-validation-for="Description" class="text-danger" />
            </div>

            <div class="form-group">
                <label>
                    Status
                </label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Hiển thị</option>
                    <option value="0">ẩn</option>
                </select>
                <span asp-validation-for="Status" class="text-danger" />
            </div>

            <div class="form-group">
                <button class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
    <a asp-action="Index">Back to list brands</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/Brand/Edit.cshtml
@model BrandModel
@{
    ViewData["title"] = "Edit Brand";
}
<h4>Edit brand</h4>
<div class="col-md-9">
    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger">
            <div class="form-group">
                <label>
                    Name
                </label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>

            <div class="form-group">
                <label>
                    Description
                </label>
                <textarea asp-for="Description" class="form-control"></textarea> <!-- Sửa lại thẻ textarea -->
                <span asp-validation-for="Description" class="text-danger" />
            </div>

            <div class="form-group">
                <label>
                    Status
                </label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Hiển thị</option>
                    <option value="0">ẩn</option>
                </select>
                <span asp-validation-for="Status" class="text-danger" />
            </div>

            <div class="form-group">
                <button class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
    <a asp-action="Index">Back to list brands</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<BrandModel>
@{
    ViewData["title"] = "Brand Listed";
}

<h3>List brand</h3>
<a asp-area="Admin" asp-action="Create" asp-controller="Brand">Add Brand</a>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Brand Name</th>
            <th scope="col">Brand Description</th>
            <th scope="col">Brand Slug</th>
            <th scope="col">Brand Status</th>
            <th scope="col">Brand Manager</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@Html.Raw(@item.Description)</td>
                <td>@item.Slug</td>
                <td>
                    @if (item.Status == 1)
                    {
                        <span class="text text-success">Hiển thị</span>
                    }
                    else
                    {
                        <span class="text text-danger">ẩn</span>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Brand" asp-route-Id="@item.Id" class="btn btn-warning btn-sm">Edit</a>
                    <a asp-action="Delete" asp-controller="Brand" asp-route-Id="@item.Id" class="btn btn-danger btn-sm confirmDeletion">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>